### ISSUE TITLE
Connection reset by peer

### ISSUE THREAD

**Issue by Dagimal** [ffreemt/bing-image-urls#1]
I really like your project, but I get a problem, I get an error like this:
 ## httpx.ConnectError: [Errno 104] Connection reset by peer

This error appeared when I was taking url for 1000 keywords

![peer](https://user-images.githubusercontent.com/25417316/106791501-93ba2480-6687-11eb-935b-2e2b813e7649.png)

**Comment by ffreemt** [comment]
I believe it's caused due to timeout. The module uses httpx to query bing.com. httpx has a default timeout of 5 seconds.

I may include a timeout parameter as an argument in the new version. In the meantime, you may wish to try setting longer socket timeout (https://docs.python.org/3/library/socket.html#socket.socket.settimeout) directly.
